[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/cinder.mp4"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="#cdd6f4"
TimeTextColor="#f5e0dc"

FormBackgroundColor="#181825"

LoginFieldBackgroundColor="#313244"
PasswordFieldBackgroundColor="#313244"

LoginFieldTextColor="#cdd6f4"
PasswordFieldTextColor="#cdd6f4"

PlaceholderTextColor="#a6adc8"

LoginButtonTextColor="#1e1e2e"
LoginButtonBackgroundColor="#f5e0dc"

SystemButtonsIconsColor="#cdd6f4"
EnvironmentButtonTextColor="#cdd6f4"

DropdownTextColor="#cdd6f4"
DropdownSelectedTextColor="#1e1e2e"
DropdownBackgroundColor="#1e1e2e"
DropdownSelectedBackgroundColor="#f5e0dc"
DropdownBorderColor="#45475a"
DropdownSelectedBorderColor="#cba6f7"

HoverLoginButtonBackgroundColor="#cba6f7"
HoverSystemButtonsIconsColor="#cba6f7"
HoverEnvironmentButtonTextColor="#cba6f7"

Blur="0.5"
FormPosition="left"
